# Generated by Django 5.1.4 on 2024-12-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaign_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='logo',
        ),
    ]
